version: '3'
services:    
  agent: 
    image: jaegertracing/jaeger-agent:1.11
    security_opt:
      - 'seccomp:unconfined'    
    restart: unless-stopped
    command: 
      # - --collector.host-port=collector:14267
      - --reporter.grpc.host-port=172.31.11.109:14250,172.31.11.109:24250
      - --log-level=debug
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778/tcp
